# Base stage
FROM node:lts AS base

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Development stage
FROM base AS development

EXPOSE 5000

CMD ["npm", "run", "dev"]

# Production stage
FROM base AS production

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "dist"]