services:
  backend:
    build: ./server
    env_file: .env.development
    depends_on:
      - db
    ports:
      - '1337:1337'
  frontend:
    build: ./client
    ports:
      - '8080:3000'
  db:
    image: mysql:5.7
    command: --max_allowed_packet=512M
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  db_data:
