services:
  backend:
    build: ./server
    env_file: .env
    depends_on:
      - db
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
  frontend:
    build: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '${FRONTEND_PORT}:3000'
      - '${FRONTEND_DEV_PORT}:5000'
    environment:
      NODE_ENV: ${ENVIRONMENT}
  db:
    image: mysql:5.7
    command: --max_allowed_packet=512M
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '4406:3306'
volumes:
  db_data:
