FROM node:lts

# Install mysql client
RUN apt-get update && apt-get install -y default-mysql-client

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# Copy SSL certificates
COPY ./.ssh/fullchain1.pem /etc/ssl/certs/fullchain.pem
COPY ./.ssh/privkey1.pem /etc/ssl/private/privkey.pem

# Copy the rest of the application files
COPY . .

CMD [ "npm", "start" ]