FROM node:lts

# Install mysql client
RUN apt-get update && apt-get install -y default-mysql-client

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY server.cert /etc/ssl/certs/server.cert
COPY server.key /etc/ssl/private/server.key

COPY . .

COPY wait-for.sh /wait-for.sh
RUN chmod +x /wait-for.sh

CMD [ "/wait-for.sh", "db", "3306", "npm", "start" ]