FROM node:lts

# Install mysql client
RUN apt-get update && apt-get install -y default-mysql-client

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# Copy SSL certificates
COPY ./.ssh/fullchain1.pem /etc/ssl/certs/fullchain.pem
COPY ./.ssh/privkey1.pem /etc/ssl/private/privkey.pem

COPY . .

COPY wait-for.sh /wait-for.sh
RUN chmod +x /wait-for.sh

# CMD [ "/wait-for.sh", "db", "3306", "npm", "start" ]
CMD [ "npm", "start" ]